remote_theme: chrisrhymes/bulma-clean-theme
title: Waterlooplein 3D
description: Eenvoudige 3D reconstructie van stratenpatroon Waterloopleinbuurt rond 1880. 
logo: https://media.githubusercontent.com/media/ElmarJ/Waterlooplein3D/master/Assets/Images/Logos/LargeTile.scale-400.png
show_downloads: false
